version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
  #      - './myadminfolder:/etc/myadminsrc'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  #      - './myadminfolder:/etc/myadminsrc'

  mysql:
    image: mysql:8
    ports:
      # {internal_in_docker}:{external_from_browser}
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'